name: CMake Qt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ qt6-base-dev qt6-datavisualization-dev

      - name: Configure
        run: |
          cmake -S . -B build

      - name: Build
        run: |
          cmake --build build